fix(mink-core.bb): handle libraries correctly
Remove temporary solution we had for the successfull build.
When temporary fix was removed following error occured:

ERROR: mink-core-1.1.5-r0 do_package_qa: QA Issue: non
-dev/-dbg/nativesdk- package mink-core contains symlink .so
'/usr/lib/libgdt.so' non -dev/-dbg/nativesdk- package mink-core
contains symlink .so '/usr/lib/mink/plg_sysagent_system.so'
 [dev-so]

We skip the dev-so check now, and add path /usr/lib/mink to be
included as part of the package.

Signed-off-by: Davor Popovic <davor.popeye@gmail.com>